package day_46_Exception;

public class ExeptionTutorial {
    public static void main(String[] args) {
        System.out.println("program başladı");
        int arr[] = new int[3];
        System.out.println(arr[3]);
        System.out.println("program bitti");

//        System.out.println("program başladı");
//        for (int i = 0; i < 5; i++) {
//            Scanner scan =new Scanner(System.in);
//            System.out.println("sayı: ");
//            int x=scan.nextInt();
//            System.out.println("bölüm");
//            int y=scan.nextInt();
//            // exeption hatası geldi nasıl düzeltebiliriz??
//            if(y!=0){
//                System.out.println("sonuç: "+(x/y));
//            }else{
//                System.out.println("bölüm 0 olamaz");
//            }
//        }

        // System.out.println("program bitti");
//
//        System.out.println("bir sayı giriniz");
//        Scanner scan =new Scanner(System.in);
//        int sayi=scan.nextInt();
//        System.out.println("program bitti");
    }
}
